import {
  Heart,
  Brain,
  Bone,
  Baby,
  Eye,
  Ear,
  Smile,
  Stethoscope,
} from "lucide-react";

export const departmentsData = [
  { name: "Cardiologist", icon: Heart },
  { name: "Neurologist", icon: Brain },
  { name: "Orthopedic", icon: Bone },
  { name: "Gynecologist", icon: Baby },
  { name: "Dentist", icon: Smile },
  { name: "General Physician", icon: Stethoscope },
  { name: "ENT Specialist", icon: Ear },
  { name: "Pediatrician", icon: Baby },
  { name: "Psychiatrist", icon: Brain },
  { name: "Gastroenterologist", icon: Stethoscope },
  { name: "Pulmonologist", icon: Stethoscope },
  { name: "Oncologist", icon: Stethoscope },
  { name: "Urologist", icon: Stethoscope },
  { name: "Nephrologist", icon: Stethoscope },
  { name: "Endocrinologist", icon: Stethoscope },
  { name: "Ophthalmologist", icon: Eye },
  { name: "Physiotherapist", icon: Bone },
  { name: "Dermatologist", icon: Smile },
  { name: "Ayurvedic", icon: Stethoscope },
  { name: "Homeopathy", icon: Stethoscope },
  { name: "Unani", icon: Stethoscope },
  { name: "Siddha", icon: Stethoscope },
  { name: "Yoga & Naturopathy", icon: Stethoscope },
];